### ISSUE TITLE
Missing token logo and social links info at Etherscan

### ISSUE THREAD

**Issue by sneg55** [Dollar-Protocol/RFC#2]
![image](https://user-images.githubusercontent.com/7769371/92047107-1d607180-ed39-11ea-8d84-c0aedf85f468.png)

https://etherscan.io/token/0xd233D1f6FD11640081aBB8db125f722b5dc729dc

**Comment by sneg55** [comment]
Same for shares

**Comment by satoshinate** [comment]
Thanks for the note! We submitted info to ether scan for both a few days ago so hopefully they respond soon :)

**Comment by satoshinate** [comment]
SHARE is up https://etherscan.io/token/0x6b583cf4aba7bf9d6f8a51b3f1f7c7b2ce59bf15
USD still waiting

**Comment by satoshinate** [comment]
USD is now up: https://etherscan.io/token/0xd233d1f6fd11640081abb8db125f722b5dc729dc

closing issue
